global:
  scrape_interval: 10s  # Intervalo de coleta de métricas

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']  # Acessa o Otel Collector para pegar as métricas expostas
